import type { Metadata } from "next";
import { Inte } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MediTrack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full mx-auto text-slate-800">
          <Navbar />
          <main className="p-4 text-lg mt-16">{children}</main>

          <footer className="text-center text-gray-600 text-sm py-4 mt-8 border-t">
            © 2025 MediTrack. All rights reserved.
          </footer>
        </div>
      </body>
    </html>
  );
}
